variables:
  VERSION: 1.0.0
  WEBAPP_DEMO: /opt/webapp/charge
  SONAR_URL: http://192.168.100.205:9000
  GITLAB_URL: https://code.haylion.cn/charge/maas-charge.git
  GITLAB_TOKEN: 9DepJ28wyRzG6mFBh9z3
  JAR_SUFFIX: 1.0-SNAPSHOT
  MODULE1: charge-auth
  MODULE2: charge-gateway
  MODULE4: charge-user
  MODULE5: charge-system
  MODULE6: charge-job

stages:
- package
- deploy

charge-auth_dev:
  stage: deploy
  when: manual
  only:
    - dev
  script:
    - ssh ${user_dev}@${host_dev} "[ ! -d ${WEBAPP_DEMO}/${MODULE1} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE1}; echo 1"
    - mvn clean package -e -Dmaven.test.skip=true
    - scp ${MODULE1}/target/${MODULE1}-${JAR_SUFFIX}.jar ${user_dev}@${host_dev}:${WEBAPP_DEMO}/${MODULE1}/.
    - ssh ${user_dev}@${host_dev} 'kill -9 `pgrep -f charge-auth-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_dev}@${host_dev} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE1}/ ; nohup java -jar ${MODULE1}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_dev}   --spring.cloud.nacos.config.server-addr=${nacos_server_dev} >> /dev/null 2>&1 &"
  tags:
    - dev

charge-gateway_dev:
  stage: deploy
  when: manual
  only:
    - dev
  script:
    - ssh ${user_dev}@${host_dev} "[ ! -d ${WEBAPP_DEMO}/${MODULE2} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE2}; echo 1"
    - mvn clean package -e -Dmaven.test.skip=true
    - scp ${MODULE2}/target/${MODULE2}-${JAR_SUFFIX}.jar ${user_dev}@${host_dev}:${WEBAPP_DEMO}/${MODULE2}/.
    - ssh ${user_dev}@${host_dev} 'kill -9 `pgrep -f charge-gateway-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_dev}@${host_dev} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE2}/ ; nohup java -jar ${MODULE2}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_dev}   --spring.cloud.nacos.config.server-addr=${nacos_server_dev} >> /dev/null 2>&1 &"
  tags:
    - dev


charge-user_dev:
  stage: deploy
  when: manual
  only:
    - dev
  script:
    - ssh ${user_dev}@${host_dev} "[ ! -d ${WEBAPP_DEMO}/${MODULE4} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE4}; echo 1"
    - mvn clean package -e -e -Dmaven.test.skip=true
    - scp ${MODULE4}/target/${MODULE4}-${JAR_SUFFIX}.jar ${user_dev}@${host_dev}:${WEBAPP_DEMO}/${MODULE4}/.
    - ssh ${user_dev}@${host_dev} 'kill -9 `pgrep -f charge-user-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_dev}@${host_dev} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE4}/ ; nohup java -jar ${MODULE4}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_dev}    --spring.cloud.nacos.config.server-addr=${nacos_server_dev} >> /dev/null 2>&1 &"
  tags:
    - dev

charge-system_dev:
  stage: deploy
  when: manual
  only:
    - dev
  script:
    - ssh ${user_dev}@${host_dev} "[ ! -d ${WEBAPP_DEMO}/${MODULE5} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE5}; echo 1"
    - mvn clean package -e -e -Dmaven.test.skip=true
    - scp ${MODULE5}/target/${MODULE5}-${JAR_SUFFIX}.jar ${user_dev}@${host_dev}:${WEBAPP_DEMO}/${MODULE5}/.
    - ssh ${user_dev}@${host_dev} 'kill -9 `pgrep -f charge-system-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_dev}@${host_dev} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE5}/ ; nohup java -jar ${MODULE5}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_dev}    --spring.cloud.nacos.config.server-addr=${nacos_server_dev} >> /dev/null 2>&1 &"
  tags:
    - dev

charge-job_dev:
  stage: deploy
  when: manual
  only:
    - dev
  script:
    - ssh ${user_dev}@${host_dev} "[ ! -d ${WEBAPP_DEMO}/${MODULE6} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE6}; echo 1"
    - mvn clean package -e -e -Dmaven.test.skip=true
    - scp ${MODULE6}/target/${MODULE6}-${JAR_SUFFIX}.jar ${user_dev}@${host_dev}:${WEBAPP_DEMO}/${MODULE6}/.
    - ssh ${user_dev}@${host_dev} 'kill -9 `pgrep -f charge-job-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_dev}@${host_dev} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE6}/ ; nohup java -jar ${MODULE6}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_dev}    --spring.cloud.nacos.config.server-addr=${nacos_server_dev} >> /dev/null 2>&1 &"
  tags:
    - dev
charge-job_pro:
  stage: deploy
  when: manual
  only:
    - pro
  script:
    - ssh ${user_pro}@${host_pro} "[ ! -d ${WEBAPP_DEMO}/${MODULE6} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE6}; echo 1"
    - mvn clean package -e -e -Dmaven.test.skip=true
    - scp ${MODULE6}/target/${MODULE6}-${JAR_SUFFIX}.jar ${user_pro}@${host_pro}:${WEBAPP_DEMO}/${MODULE6}/.
    - ssh ${user_pro}@${host_pro} 'kill -9 `pgrep -f charge-job-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_pro}@${host_pro} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE6}/ ; nohup java -jar ${MODULE6}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_pro} --spring.cloud.nacos.discovery.namespace=${charge_namespace_pro}   --spring.cloud.nacos.config.server-addr=${nacos_server_pro} --spring.cloud.nacos.discovery.server-addr=${nacos_server_pro}>> /dev/null 2>&1 &"
  tags:
    - dev



charge-auth_pro:
  stage: deploy
  when: manual
  only:
    - pro
  script:
    - ssh ${user_pro}@${host_pro} "[ ! -d ${WEBAPP_DEMO}/${MODULE1} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE1}; echo 1"
    - mvn clean package -e -Dmaven.test.skip=true
    - scp ${MODULE1}/target/${MODULE1}-${JAR_SUFFIX}.jar ${user_pro}@${host_pro}:${WEBAPP_DEMO}/${MODULE1}/.
    - ssh ${user_pro}@${host_pro} 'kill -9 `pgrep -f charge-auth-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_pro}@${host_pro} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE1}/ ; nohup java -jar ${MODULE1}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_pro} --spring.cloud.nacos.discovery.namespace=${charge_namespace_pro}  --spring.cloud.nacos.config.server-addr=${nacos_server_pro} --spring.cloud.nacos.discovery.server-addr=${nacos_server_pro}>> /dev/null 2>&1 &"
  tags:
    - dev

charge-gateway_pro:
  stage: deploy
  when: manual
  only:
    - pro
  script:
    - ssh ${user_pro}@${host_pro} "[ ! -d ${WEBAPP_DEMO}/${MODULE2} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE2}; echo 1"
    - mvn clean package -e -Dmaven.test.skip=true
    - scp ${MODULE2}/target/${MODULE2}-${JAR_SUFFIX}.jar ${user_pro}@${host_pro}:${WEBAPP_DEMO}/${MODULE2}/.
    - ssh ${user_pro}@${host_pro} 'kill -9 `pgrep -f charge-gateway-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_pro}@${host_pro} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE2}/ ; nohup java -jar ${MODULE2}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_pro} --spring.cloud.nacos.discovery.namespace=${charge_namespace_pro} --spring.cloud.nacos.config.server-addr=${nacos_server_pro} --spring.cloud.nacos.discovery.server-addr=${nacos_server_pro}>> /dev/null 2>&1 &"
  tags:
    - dev


charge-user_pro:
  stage: deploy
  when: manual
  only:
    - pro
  script:
    - ssh ${user_pro}@${host_pro} "[ ! -d ${WEBAPP_DEMO}/${MODULE4} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE4}; echo 1"
    - mvn clean package -e -Dmaven.test.skip=true
    - scp ${MODULE4}/target/${MODULE4}-${JAR_SUFFIX}.jar ${user_pro}@${host_pro}:${WEBAPP_DEMO}/${MODULE4}/.
    - ssh ${user_pro}@${host_pro} 'kill -9 `pgrep -f charge-user-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_pro}@${host_pro} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE4}/ ; nohup java -jar ${MODULE4}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_pro} --spring.cloud.nacos.discovery.namespace=${charge_namespace_pro}  --spring.cloud.nacos.config.server-addr=${nacos_server_pro} --spring.cloud.nacos.discovery.server-addr=${nacos_server_pro}>> /dev/null 2>&1 &"
  tags:
    - dev

charge-system_pro:
  stage: deploy
  when: manual
  only:
    - pro
  script:
    - ssh ${user_pro}@${host_pro} "[ ! -d ${WEBAPP_DEMO}/${MODULE5} ] && mkdir -p ${WEBAPP_DEMO}/${MODULE5}; echo 1"
    - mvn clean package -e -Dmaven.test.skip=true
    - scp ${MODULE5}/target/${MODULE5}-${JAR_SUFFIX}.jar ${user_pro}@${host_pro}:${WEBAPP_DEMO}/${MODULE5}/.
    - ssh ${user_pro}@${host_pro} 'kill -9 `pgrep -f charge-system-1.0-SNAPSHOT\.jar` ; echo 1'
    - ssh ${user_pro}@${host_pro} ". /etc/profile ; cd ${WEBAPP_DEMO}/${MODULE5}/ ; nohup java -jar ${MODULE5}-${JAR_SUFFIX}.jar --spring.cloud.nacos.config.namespace=${charge_namespace_pro} --spring.cloud.nacos.discovery.namespace=${charge_namespace_pro}  --spring.cloud.nacos.config.server-addr=${nacos_server_pro} --spring.cloud.nacos.discovery.server-addr=${nacos_server_pro}>> /dev/null 2>&1 &"
  tags:
    - dev
